import csv
import io

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session

from backend.database.database import SessionLocal
from backend.schemas.analytics import (
    AIAnalystRequest,
    AIAnalystResponse,
    CategoryRevenueResponse,
    ProductDataResponse,
    ProductForecastResponse,
    ProductRevenueResponse,
    RevenueTrendResponse,
    SalesDataResponse,
    VendorAnalyticsResponse,
    VendorBenchmarkResponse
)
from backend.services.ai_analyst import answer_question
from backend.crud.analytics import (
    get_sales_data,
    get_product_data,
    get_vendor_analytics,
    get_product_forecast,
    get_revenue_by_product,
    get_revenue_by_category,
    get_revenue_trend,
    get_vendor_benchmarks,
    get_vendor_benchmark,
    get_transaction_report_rows
)


router = APIRouter(
    prefix="/analytics",
    tags=["Analytics"]
)


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


@router.get(
    "/sales",
    response_model=list[SalesDataResponse],
    summary="Get Aggregated Sales by Product",
    description="Aggregates sales amounts for each product based on historical purchase transactions.",
    response_description="List of products with total sales amount"
)
def sales_analytics(
    db: Session = Depends(get_db)
):
    """
    Retrieve product sales totals for dashboard visualizations.
    """
    return get_sales_data(db)


@router.get(
    "/products",
    response_model=list[ProductDataResponse],
    summary="Get Unique Product Names",
    description="Retrieves a list of distinct product names currently recorded in the product catalog.",
    response_description="List of unique product names"
)
def product_analytics(
    db: Session = Depends(get_db)
):
    """
    Fetch unique product names.
    """
    return get_product_data(db)


@router.get(
    "/vendors",
    response_model=list[VendorAnalyticsResponse],
    summary="Get Vendor Sales & Revenue Analytics",
    description="Calculates transaction count and gross revenue per vendor.",
    response_description="Vendor performance metrics including sales volume and revenue"
)
def vendor_analytics(
    db: Session = Depends(get_db)
):
    """
    Compute sales count and total revenue generated by each vendor.
    """
    return get_vendor_analytics(db)


@router.get(
    "/revenue-by-product",
    response_model=list[ProductRevenueResponse],
    summary="Get Revenue by Product",
    description="Calculates total revenue generated broken down by individual product.",
    response_description="List of products with cumulative revenue"
)
def revenue_by_product(
    db: Session = Depends(get_db)
):
    """
    Break down platform revenue on a per-product basis.
    """
    return get_revenue_by_product(db)


@router.get(
    "/revenue-by-category",
    response_model=list[CategoryRevenueResponse],
    summary="Get Revenue by Category",
    description="Aggregates platform revenue grouped by product category.",
    response_description="Category revenue breakdown"
)
def revenue_by_category(
    db: Session = Depends(get_db)
):
    """
    Aggregate transaction revenues by category.
    """
    return get_revenue_by_category(db)


@router.get(
    "/revenue-trend",
    response_model=list[RevenueTrendResponse],
    summary="Get Daily Revenue Trend",
    description="Generates a daily timeline of revenue and transaction counts across all historical recorded dates.",
    response_description="Time series of daily revenue and transaction count"
)
def revenue_trend(
    db: Session = Depends(get_db)
):
    """
    Generate date-by-date revenue progression for trend charting.
    """
    return get_revenue_trend(db)


@router.get(
    "/vendor-benchmark",
    response_model=list[VendorBenchmarkResponse],
    summary="Get Vendor Benchmarks",
    description="Compares each vendor's revenue performance against the marketplace average, classifying them as 'Above Average', 'Below Average', or 'At Average'.",
    response_description="Marketplace benchmark comparisons for all vendors"
)
def vendor_benchmark_list(
    db: Session = Depends(get_db)
):
    """
    Calculate performance benchmarks across all active vendors.
    """
    return get_vendor_benchmarks(db)


@router.get(
    "/vendor-benchmark/{vendor_id}",
    response_model=VendorBenchmarkResponse,
    summary="Get Benchmark for a Single Vendor",
    description="Retrieves the detailed performance benchmark for an individual vendor by vendor ID.",
    response_description="Vendor benchmark details and difference vs marketplace average",
    responses={
        404: {"description": "Vendor not found"}
    }
)
def vendor_benchmark_detail(
    vendor_id: int,
    db: Session = Depends(get_db)
):
    """
    Retrieve benchmark metrics for a single vendor.
    """
    benchmark = get_vendor_benchmark(db, vendor_id)
    if benchmark is None:
        raise HTTPException(status_code=404, detail="Vendor not found")
    return benchmark


@router.get(
    "/export/csv",
    summary="Export Transactions CSV Report",
    description="Generates and streams a downloadable CSV file containing all transaction details for offline accounting or reporting.",
    response_description="Streaming CSV file download"
)
def export_transaction_csv(
    db: Session = Depends(get_db)
):
    """
    Export all transactions into a downloadable CSV report.
    """
    fieldnames = [
        "Transaction ID",
        "Transaction Date",
        "Product Name",
        "Customer Name",
        "Vendor ID",
        "Amount"
    ]
    output = io.StringIO(newline="")
    writer = csv.DictWriter(output, fieldnames=fieldnames, lineterminator="\n")
    writer.writeheader()
    writer.writerows(get_transaction_report_rows(db))
    output.seek(0)

    return StreamingResponse(
        iter([output.getvalue()]),
        media_type="text/csv; charset=utf-8",
        headers={
            "Content-Disposition": "attachment; filename=shopsense_sales_report.csv"
        }
    )


@router.get(
    "/forecast",
    response_model=ProductForecastResponse,
    summary="Forecast Product Demand",
    description="Calculates a forward-looking daily demand forecast for a given product using recent moving average transaction sales.",
    response_description="Forecasted daily demand units for requested forecast window"
)
def product_forecast(
    product_name: str = Query(..., min_length=1, description="Exact product name to forecast", examples=["Laptop"]),
    forecast_days: int = Query(7, ge=1, le=30, description="Number of future days to forecast (1-30)", examples=[7]),
    db: Session = Depends(get_db)
):
    """
    Forecast demand units for a product using moving average historical transactions.
    """
    return get_product_forecast(
        db,
        product_name,
        forecast_days
    )


@router.post(
    "/ai/query",
    response_model=AIAnalystResponse,
    summary="Query AI Business Analyst",
    description="Submits a natural language question about ShopSense platform data. Interprets query, runs safe read-only SQL, and returns human summary.",
    response_description="AI analysis answer with supporting data and SQL"
)
def ai_query(
    request: AIAnalystRequest,
    db: Session = Depends(get_db)
):
    """
    Process natural language queries against the ShopSense SQLite database with strict read-only guarantees.
    """
    return answer_question(db, request.question)
