from typing import Any

from pydantic import BaseModel, Field


class AIAnalystRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        max_length=500,
        description="Natural language question about ShopSense sales, products, vendors, or customers",
        examples=["What is the total revenue?", "Which product sold the most?"]
    )


class AIAnalystResponse(BaseModel):
    question: str = Field(..., description="The original question asked")
    answer: str = Field(..., description="Human-readable summary answer")
    sql: str | None = Field(default=None, description="Read-only SQLite query generated and executed, if any")
    data: list[dict[str, Any]] = Field(default_factory=list, description="Raw query result rows")
    provider: str = Field(..., description="Resolution provider ('openai' or 'local')")
    status: str = Field(..., description="Execution status code")


class SalesDataResponse(BaseModel):
    product: str = Field(..., description="Product display name", examples=["Laptop"])
    amount: float = Field(..., description="Total sales amount in INR", examples=[50000.0])


class ProductDataResponse(BaseModel):
    product: str = Field(..., description="Unique product display name", examples=["Laptop"])


class VendorAnalyticsResponse(BaseModel):
    vendor_id: int = Field(..., description="Unique vendor ID", examples=[1])
    vendor_name: str = Field(..., description="Business name of the vendor", examples=["Tech Corp"])
    total_sales: int = Field(..., description="Total number of completed transactions", examples=[12])
    total_revenue: float = Field(..., description="Total revenue generated by the vendor in INR", examples=[24500.0])


class ProductRevenueResponse(BaseModel):
    product: str = Field(..., description="Product name", examples=["Laptop"])
    revenue: float = Field(..., description="Total revenue generated by this product in INR", examples=[150000.0])


class CategoryRevenueResponse(BaseModel):
    category: str = Field(..., description="Category name", examples=["Electronics"])
    revenue: float = Field(..., description="Total revenue generated by this category in INR", examples=[230000.0])


class RevenueTrendResponse(BaseModel):
    date: str = Field(..., description="ISO 8601 date string (YYYY-MM-DD)", examples=["2026-03-01"])
    revenue: float = Field(..., description="Total revenue on this date in INR", examples=[12500.0])
    transactions: int = Field(..., description="Number of transactions on this date", examples=[4])


class VendorBenchmarkResponse(BaseModel):
    vendor_id: int = Field(..., description="Unique vendor ID", examples=[1])
    vendor_name: str = Field(..., description="Business name", examples=["Tech Corp"])
    vendor_revenue: float = Field(..., description="Vendor total revenue in INR", examples=[75000.0])
    marketplace_average_revenue: float = Field(..., description="Average revenue across all marketplace vendors in INR", examples=[50000.0])
    difference: float = Field(..., description="Difference from marketplace average", examples=[25000.0])
    percentage_vs_average: float = Field(..., description="Percentage relative to marketplace average", examples=[50.0])
    status: str = Field(..., description="Performance status relative to marketplace ('Above Average', 'Below Average', 'At Average')", examples=["Above Average"])
    marketplace_vendor_count: int = Field(..., description="Total count of marketplace vendors", examples=[5])
    average_definition: str = Field(..., description="Explanation of how the benchmark average was computed")


class ForecastDataPoint(BaseModel):
    date: str = Field(..., description="Forecasted date in YYYY-MM-DD format", examples=["2026-03-10"])
    predicted_demand: float = Field(..., description="Predicted demand / sales units for this day", examples=[2.5])


class ProductForecastResponse(BaseModel):
    product_name: str = Field(..., description="Name of the forecasted product", examples=["Laptop"])
    forecast_days: int = Field(..., description="Number of days forecasted ahead", examples=[7])
    forecast: list[ForecastDataPoint] = Field(default_factory=list, description="Day-by-day forecasted demand")
    status: str = Field(..., description="Forecast calculation status ('success', 'insufficient_data', 'not_found')", examples=["success"])
    message: str = Field(..., description="Explanation or status description")
    historical_days: int | None = Field(default=None, description="Span of historical transaction days observed")
    sales_days: int | None = Field(default=None, description="Number of days with recorded transactions")

